server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/**,/reservationinquiries/**
        - id: Reservationmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/hotelReservationManagements/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: point
          uri: http://localhost:8084
          predicates:
            - Path=/points/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://skccuser2-reservation:8080
          predicates:
            - Path=/reservations/**,/reservationinquiries/**
        - id: Reservationmanagement
          uri: http://skccuser2-reservationmanagement:8080
          predicates:
            - Path=/hotelReservationManagements/** 
        - id: payment
          uri: http://skccuser2-payment:8080
          predicates:
            - Path=/payments/** 
        - id: point
          uri: http://skccuser2-point:8080
          predicates:
            - Path=/points/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
